### ISSUE TITLE
Temperature parsed as -273 degrees

### ISSUE THREAD

**Issue by UNFPAmaldives** [prcwiek/pmetar#1]
The following parses the temperature as -273 degrees:

```
x <- "201905070355 METAR KDCA 070355Z AUTO 20005KT 10SM CLR A3010 RMK T0180 MADISHF"
df <- metar_decode(x, as_data_frame = TRUE)
```

**Comment by prcwiek** [comment]
Thank you for checking and sorry for a very huge delay to correct. I didn't suppose that anybody would be interested in this library.
