### ISSUE TITLE
metar_decode function error when using large datasets

### ISSUE THREAD

**Issue by franciscoleoncrz** [prcwiek/pmetar#7]
Hi. First of all, thank you so much for your work. 

I'm having an issue with the metar_decode function. The function works well when I use this function for a relatively small dataset (I mean a year of data for one airport). However, when I tried to use it with a bigger data sample (more than a year), an error displayed with the following sentence "Error: pmetar package error: Incorrect METAR weather report found and cannot be decoded!" 

It is essential to mention that I also use the function metar_is_correct (and remove the incorrect data) before using the decode function. 

Thanks!

**Comment by prcwiek** [comment]
Hi,
Thanks for pointing out the problem. Would you be able to provide an airport code, star_date and end_date? I will download a data set and take a look.

**Comment by franciscoleoncrz** [comment]
Hi, 
Thanks for your quick answer!
Sure, the airport code is "MMGL," and the problem is for the METARs from the 2000 year (i.e., 2000-01-01, 2000-12-31). I tried to figure out the problem but have not had luck. 

Thanks!
